services:
  nginx:
    image: nginx:latest
    container_name: basic-nginx
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./conf.d:/etc/nginx/conf.d
      - ./logs:/var/log/nginx
      - ./cert:/etc/nginx/cert
      - ./html:/usr/share/nginx/wwwroot

networks:
  default:
    name: ${NETWORK_NAME:-basic-network}
    external: true
